# Generated by Django 3.2.6 on 2021-09-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('studentcollege', models.CharField(max_length=100)),
                ('studentrollnumber', models.IntegerField()),
                ('studentbranch', models.CharField(max_length=50)),
            ],
        ),
    ]
